// Polyfills
import 'es6-shim';
import 'es6-promise';
//import 'angular2-polyfills';
import 'es7-reflect-metadata/dist/browser';
import 'zone.js/lib/browser/zone-microtask';
import 'zone.js/lib/zones/long-stack-trace';
import 'jquery/dist/jquery';
// RxJS
import 'rxjs';
